name: "Setup Vagrant"
description: "Setup your GitHub Actions workflow with HashiCorp Vagrant."
inputs:
  exec:
    description: "HashiCorp Vagrant command to execute"
    required: true
author: "rkialashaki"
branding:
  color: black
  icon: cpu

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.exec }}
