name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use rkialashaki/setup-vagrant
      uses: ./
      with:
        exec: |
          vagrant init -m hashicorp/bionic64 && \
          vagrant up
