name: "Continuous Integration"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use oxr463/setup-vagrant
      uses: ./
      with:
        exec: |
          VBoxManage --version && \
          vagrant init -m hashicorp/bionic64 && \
          vagrant up
